In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN

model = Sequential()
model.add(SimpleRNN(3, input_shape = (2, 10)))
# model.add(SimpleRNN(hidden_units, input_shape = (timesteps, input_dim)))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


In [3]:
model = Sequential()
# timesteps = input_length
model.add(SimpleRNN(3, input_length = 2, input_dim = 10))
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


### USE batch

In [4]:
model = Sequential()
# model.add(SimpleRNN(hidden unit,
# batch_input_shape = (batch_size , timesteps(input_length), input_dim))) 
model.add(SimpleRNN(3, batch_input_shape = (8,2,10)))
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_2 (SimpleRNN)    (8, 3)                    42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


### Use batch / resturn_sequence = True

In [5]:
model = Sequential()
# model.add(SimpleRNN(hidden unit,
# batch_input_shape = (batch_size , timesteps(input_length), input_dim))) 
model.add(SimpleRNN(3, batch_input_shape = (8,2,10), return_sequences = True))
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_3 (SimpleRNN)    (8, 2, 3)                 42        
                                                                 
Total params: 42
Trainable params: 42
Non-trainable params: 0
_________________________________________________________________


### 깊은 순환신경망

In [6]:
model = Sequential()
# timesteps = input_length
model.add(SimpleRNN(3, input_length = 10, input_dim = 5, return_sequences=True))
model.add(SimpleRNN(3, return_sequences=True))
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_4 (SimpleRNN)    (None, 10, 3)             27        
                                                                 
 simple_rnn_5 (SimpleRNN)    (None, 10, 3)             21        
                                                                 
Total params: 48
Trainable params: 48
Non-trainable params: 0
_________________________________________________________________


# Simple RNN(use Data)

In [7]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import SimpleRNN, LSTM

# time step 4, input_dim = 5, batch_size = 1
train_X = [[
    [0.1, 4.2, 1.5, 1.1, 2.8], 
    [1.0, 3.1, 2.5, 0.7, 1.1],
    [0.3, 2.1, 1.5, 2.1, 0.1],
    [2.2, 1.4, 0.5, 0.9, 1.1]
    ]]
train_X = np.array(train_X, dtype=np.float32)
print(train_X.shape)

(1, 4, 5)


### hidden_unit = 3

In [10]:
rnn = SimpleRNN(3)
hidden_states = rnn(train_X)
print(f'input shape : {train_X.shape}')
print(train_X)
print(f'hidden(output) shape : {hidden_states.shape}')
print(hidden_states)

input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
hidden(output) shape : (1, 3)
tf.Tensor([[0.21828939 0.9771939  0.6320188 ]], shape=(1, 3), dtype=float32)


### hidden_unit = 3, return_sequence = True

In [15]:
rnn = SimpleRNN(3, return_sequences = True)
hidden_states = rnn(train_X)
print(f'input shape : {train_X.shape}')
print(train_X)
print(hidden_states)

input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
tf.Tensor(
[[[-0.9957147   0.884324   -0.9973476 ]
  [-0.47035003  0.9732885  -0.4946775 ]
  [-0.27818242  0.97672635 -0.7742605 ]
  [-0.8114211   0.6069432  -0.5002982 ]]], shape=(1, 4, 3), dtype=float32)


### hidden_unit = 3, return_sequence = True, return_state = True
- return_state = True인 경우에는 return_sequence의 True/False와 관계없이 last_states는 마지막 hidden state를 출력

In [20]:
rnn = SimpleRNN(3, return_sequences = True, return_state = True)
hidden_states, last_states = rnn(train_X)
print('-----input-----')
print(f'input shape : {train_X.shape}')
print(train_X)
print('-----hidden-----')
print(hidden_states)
print('-----last-----')
print(last_states)

-----input-----
input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
-----hidden-----
tf.Tensor(
[[[-0.9999435   0.28743494 -0.8750074 ]
  [-0.9996855  -0.80370015 -0.96402025]
  [-0.98800135 -0.96756023  0.1724608 ]
  [-0.6103176  -0.68760747 -0.23966326]]], shape=(1, 4, 3), dtype=float32)
-----last-----
tf.Tensor([[-0.6103176  -0.68760747 -0.23966326]], shape=(1, 3), dtype=float32)


### hidden_unit = 3, return_sequence = False, return_state = True

In [21]:
rnn = SimpleRNN(3, return_sequences = False, return_state = True)
hidden_states, last_states = rnn(train_X)
print('-----input-----')
print(f'input shape : {train_X.shape}')
print(train_X)
print('-----hidden-----')
print(hidden_states)
print('-----last-----')
print(last_states)

-----input-----
input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
-----hidden-----
tf.Tensor([[ 0.99973714 -0.8779123  -0.49384183]], shape=(1, 3), dtype=float32)
-----last-----
tf.Tensor([[ 0.99973714 -0.8779123  -0.49384183]], shape=(1, 3), dtype=float32)


# LSTM

### return_sequences = False, return_state = True

In [23]:
lstm = LSTM(3, return_sequences = False, return_state = True)
hidden_states, last_states, last_cell_state = lstm(train_X)
print('-----input-----')
print(f'input shape : {train_X.shape}')
print(train_X)
print('-----hidden-----')
print(hidden_states)
print('-----last-----')
print(last_states)
print('-----last cell-----')
print(last_cell_state)

-----input-----
input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
-----hidden-----
tf.Tensor([[0.12877505 0.5519113  0.03305651]], shape=(1, 3), dtype=float32)
-----last-----
tf.Tensor([[0.12877505 0.5519113  0.03305651]], shape=(1, 3), dtype=float32)
-----last cell-----
tf.Tensor([[0.9979991  1.1556823  0.14465845]], shape=(1, 3), dtype=float32)


### return_sequences = True, return_state = True

In [24]:
lstm = LSTM(3, return_sequences = True, return_state = True)
hidden_states, last_states, last_cell_state = lstm(train_X)
print('-----input-----')
print(f'input shape : {train_X.shape}')
print(train_X)
print('-----hidden-----')
print(hidden_states)
print('-----last-----')
print(last_states)
print('-----last cell-----')
print(last_cell_state)

-----input-----
input shape : (1, 4, 5)
[[[0.1 4.2 1.5 1.1 2.8]
  [1.  3.1 2.5 0.7 1.1]
  [0.3 2.1 1.5 2.1 0.1]
  [2.2 1.4 0.5 0.9 1.1]]]
-----hidden-----
tf.Tensor(
[[[-0.03384799  0.07929118 -0.5639901 ]
  [-0.12900284 -0.09669468 -0.67697406]
  [-0.11185682 -0.09116451 -0.5312977 ]
  [-0.33711457 -0.30565384 -0.52453905]]], shape=(1, 4, 3), dtype=float32)
-----last-----
tf.Tensor([[-0.33711457 -0.30565384 -0.52453905]], shape=(1, 3), dtype=float32)
-----last cell-----
tf.Tensor([[-0.40749246 -0.430528   -1.645676  ]], shape=(1, 3), dtype=float32)
